const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="saimsamsun789@gmail.com"
global.location="Lahore,Pakistan."


global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "null"
global.DATABASE_URL = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://github.com/SuhailTechInfo/Suhail-Md/blob/main/lib/assets/suhail.jpg?raw=true" ; // SET LOGO FOR IMAGE 
global.caption = process.env.CAPTION || global.caption || "ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ" 


global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "923184474176";




//========================= [ BOT SETTINGS ] ======8===================\\
global.style = process.env.STYLE   || Math.floor(Math.random()*6) || '0'  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || process.env.CAN_GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || process.env.CAN_WELCOME || "false";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3
global.disablepm = process.env.DISABLE_PM || "false"
global.disablegroup = process.env.DISABLE_GROUPS || "false", // disable bot in groups when public mode

global.MsgsInLog = process.env.MSGS_IN_LOG|| "false" // "true"  to see messages , "log" to show logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES || "text" // "text" // set Image/video urls here
global.waPresence= process.env.WAPRESENCE ||  "null" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "null,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "true"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd.onrender.com" //  || "https://api-smd-1.vercel.app" // expires
global.scan = "https://suhail-md-vtsf.onrender.com";


global.SESSION_ID = process.env.SESSION_ID ||  ""  // PUT your SESSION_ID 
SUHAIL_08_31_07_09_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgNzIsXG4gICAgICAgIDI4LFxuICAgICAgICAxMzAsXG4gICAgICAgIDIyMixcbiAgICAgICAgMTc3LFxuICAgICAgICAxMTksXG4gICAgICAgIDE1MSxcbiAgICAgICAgMjgsXG4gICAgICAgIDE5MSxcbiAgICAgICAgMjUyLFxuICAgICAgICA0MyxcbiAgICAgICAgODIsXG4gICAgICAgIDIyOSxcbiAgICAgICAgMjMyLFxuICAgICAgICAxMzcsXG4gICAgICAgIDEzMSxcbiAgICAgICAgMjIyLFxuICAgICAgICAyMTEsXG4gICAgICAgIDk3LFxuICAgICAgICAxNTksXG4gICAgICAgIDM2LFxuICAgICAgICA3NixcbiAgICAgICAgNyxcbiAgICAgICAgMTc3LFxuICAgICAgICAxMixcbiAgICAgICAgNjgsXG4gICAgICAgIDEzMyxcbiAgICAgICAgMTcxLFxuICAgICAgICA3MCxcbiAgICAgICAgMTg5LFxuICAgICAgICAyMjksXG4gICAgICAgIDEwM1xuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA4MyxcbiAgICAgICAgMTQxLFxuICAgICAgICAxMTgsXG4gICAgICAgIDEwOSxcbiAgICAgICAgNyxcbiAgICAgICAgMTk3LFxuICAgICAgICAyMjksXG4gICAgICAgIDEzMCxcbiAgICAgICAgMjQyLFxuICAgICAgICAxODUsXG4gICAgICAgIDE2OCxcbiAgICAgICAgMTQxLFxuICAgICAgICAxMDQsXG4gICAgICAgIDI0NSxcbiAgICAgICAgMTg5LFxuICAgICAgICAyNSxcbiAgICAgICAgNTEsXG4gICAgICAgIDI0NyxcbiAgICAgICAgMTAsXG4gICAgICAgIDE5MyxcbiAgICAgICAgODUsXG4gICAgICAgIDEwMixcbiAgICAgICAgMjQxLFxuICAgICAgICAxNTUsXG4gICAgICAgIDIzMCxcbiAgICAgICAgMTU3LFxuICAgICAgICAxMzEsXG4gICAgICAgIDEwOCxcbiAgICAgICAgMTM1LFxuICAgICAgICAyNDcsXG4gICAgICAgIDEzNSxcbiAgICAgICAgMTE3XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyXCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyNCxcbiAgICAgICAgNzgsXG4gICAgICAgIDI0NyxcbiAgICAgICAgNzgsXG4gICAgICAgIDY0LFxuICAgICAgICA1MyxcbiAgICAgICAgMTUxLFxuICAgICAgICAxNDUsXG4gICAgICAgIDI1NCxcbiAgICAgICAgNixcbiAgICAgICAgNjEsXG4gICAgICAgIDExOSxcbiAgICAgICAgMjMzLFxuICAgICAgICA5OCxcbiAgICAgICAgMTE5LFxuICAgICAgICAxMzMsXG4gICAgICAgIDEyMCxcbiAgICAgICAgNzgsXG4gICAgICAgIDY4LFxuICAgICAgICAxNjAsXG4gICAgICAgIDEyMixcbiAgICAgICAgMTUxLFxuICAgICAgICAyNixcbiAgICAgICAgOTQsXG4gICAgICAgIDI1MyxcbiAgICAgICAgMjE3LFxuICAgICAgICAxMTEsXG4gICAgICAgIDM0LFxuICAgICAgICAzMixcbiAgICAgICAgODQsXG4gICAgICAgIDk4LFxuICAgICAgICA3N1xuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyNCxcbiAgICAgICAgNzQsXG4gICAgICAgIDEwOCxcbiAgICAgICAgMTUwLFxuICAgICAgICA5NixcbiAgICAgICAgNzYsXG4gICAgICAgIDE0MCxcbiAgICAgICAgMjIyLFxuICAgICAgICA2NCxcbiAgICAgICAgMTA2LFxuICAgICAgICAxMzcsXG4gICAgICAgIDU2LFxuICAgICAgICAyMjMsXG4gICAgICAgIDI1MCxcbiAgICAgICAgMTQsXG4gICAgICAgIDIyNixcbiAgICAgICAgNTMsXG4gICAgICAgIDE2OSxcbiAgICAgICAgMTkyLFxuICAgICAgICAyMjEsXG4gICAgICAgIDQsXG4gICAgICAgIDEwNCxcbiAgICAgICAgMjA0LFxuICAgICAgICAxMTQsXG4gICAgICAgIDYsXG4gICAgICAgIDIzMCxcbiAgICAgICAgMTgsXG4gICAgICAgIDEwNCxcbiAgICAgICAgMTk0LFxuICAgICAgICAyMDIsXG4gICAgICAgIDI0MSxcbiAgICAgICAgMTA5XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZElkZW50aXR5S2V5XCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyNDAsXG4gICAgICAgIDExLFxuICAgICAgICA2NyxcbiAgICAgICAgMjM1LFxuICAgICAgICAyMzgsXG4gICAgICAgIDExNCxcbiAgICAgICAgMTU1LFxuICAgICAgICAxNzMsXG4gICAgICAgIDI1MyxcbiAgICAgICAgMTgwLFxuICAgICAgICA3MCxcbiAgICAgICAgMzksXG4gICAgICAgIDE1OCxcbiAgICAgICAgMjUyLFxuICAgICAgICAyMzksXG4gICAgICAgIDEwMCxcbiAgICAgICAgNjYsXG4gICAgICAgIDQ0LFxuICAgICAgICA4MyxcbiAgICAgICAgMjIzLFxuICAgICAgICA3MCxcbiAgICAgICAgMTA0LFxuICAgICAgICAxNzMsXG4gICAgICAgIDE0NyxcbiAgICAgICAgMTQ2LFxuICAgICAgICAyMjIsXG4gICAgICAgIDQ5LFxuICAgICAgICAxNjQsXG4gICAgICAgIDE0NyxcbiAgICAgICAgMTIyLFxuICAgICAgICA2NSxcbiAgICAgICAgNjlcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTkzLFxuICAgICAgICAxOSxcbiAgICAgICAgMTQxLFxuICAgICAgICAxOSxcbiAgICAgICAgMTQ2LFxuICAgICAgICA2MCxcbiAgICAgICAgMTQ1LFxuICAgICAgICAyMTAsXG4gICAgICAgIDIyMCxcbiAgICAgICAgMTUwLFxuICAgICAgICAyMzIsXG4gICAgICAgIDIyMyxcbiAgICAgICAgMTQ1LFxuICAgICAgICAyMDAsXG4gICAgICAgIDAsXG4gICAgICAgIDEsXG4gICAgICAgIDExLFxuICAgICAgICAxNzAsXG4gICAgICAgIDg2LFxuICAgICAgICAxODIsXG4gICAgICAgIDI0MCxcbiAgICAgICAgODUsXG4gICAgICAgIDEwMSxcbiAgICAgICAgMTI5LFxuICAgICAgICAyMjMsXG4gICAgICAgIDIxMyxcbiAgICAgICAgMTAyLFxuICAgICAgICAyMTcsXG4gICAgICAgIDYxLFxuICAgICAgICA3NyxcbiAgICAgICAgMjM1LFxuICAgICAgICAzMVxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRQcmVLZXlcIjoge1xuICAgIFwia2V5UGFpclwiOiB7XG4gICAgICBcInByaXZhdGVcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAxMzYsXG4gICAgICAgICAgMTM0LFxuICAgICAgICAgIDgsXG4gICAgICAgICAgMTA1LFxuICAgICAgICAgIDEzMCxcbiAgICAgICAgICAxODIsXG4gICAgICAgICAgMzIsXG4gICAgICAgICAgOTQsXG4gICAgICAgICAgMjUxLFxuICAgICAgICAgIDIwLFxuICAgICAgICAgIDE4NCxcbiAgICAgICAgICAxNDEsXG4gICAgICAgICAgNjMsXG4gICAgICAgICAgMTMsXG4gICAgICAgICAgMjM1LFxuICAgICAgICAgIDg0LFxuICAgICAgICAgIDE4MCxcbiAgICAgICAgICA1OCxcbiAgICAgICAgICAxNzcsXG4gICAgICAgICAgNTMsXG4gICAgICAgICAgMjQ0LFxuICAgICAgICAgIDIwMyxcbiAgICAgICAgICAxNyxcbiAgICAgICAgICAyMzAsXG4gICAgICAgICAgMjUwLFxuICAgICAgICAgIDQzLFxuICAgICAgICAgIDQ2LFxuICAgICAgICAgIDEyMixcbiAgICAgICAgICAyMCxcbiAgICAgICAgICAyNTUsXG4gICAgICAgICAgMTQwLFxuICAgICAgICAgIDgyXG4gICAgICAgIF1cbiAgICAgIH0sXG4gICAgICBcInB1YmxpY1wiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDE0LFxuICAgICAgICAgIDk4LFxuICAgICAgICAgIDEzMyxcbiAgICAgICAgICAyMTIsXG4gICAgICAgICAgNjYsXG4gICAgICAgICAgMTUsXG4gICAgICAgICAgMTc0LFxuICAgICAgICAgIDksXG4gICAgICAgICAgNixcbiAgICAgICAgICAxMzYsXG4gICAgICAgICAgMTk1LFxuICAgICAgICAgIDIxNyxcbiAgICAgICAgICAyMzAsXG4gICAgICAgICAgNjUsXG4gICAgICAgICAgMTQxLFxuICAgICAgICAgIDMsXG4gICAgICAgICAgMjAsXG4gICAgICAgICAgMTc4LFxuICAgICAgICAgIDMzLFxuICAgICAgICAgIDEwOCxcbiAgICAgICAgICA3LFxuICAgICAgICAgIDQzLFxuICAgICAgICAgIDQsXG4gICAgICAgICAgMTEyLFxuICAgICAgICAgIDIxNCxcbiAgICAgICAgICAxMTIsXG4gICAgICAgICAgMTc4LFxuICAgICAgICAgIDU0LFxuICAgICAgICAgIDE0NSxcbiAgICAgICAgICA1MSxcbiAgICAgICAgICAxNzEsXG4gICAgICAgICAgMTI1XG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9LFxuICAgIFwic2lnbmF0dXJlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgOTcsXG4gICAgICAgIDI5LFxuICAgICAgICAxNTIsXG4gICAgICAgIDIwOCxcbiAgICAgICAgMjAzLFxuICAgICAgICA0NCxcbiAgICAgICAgMTIyLFxuICAgICAgICAxNzUsXG4gICAgICAgIDIzMSxcbiAgICAgICAgMzYsXG4gICAgICAgIDAsXG4gICAgICAgIDIzNCxcbiAgICAgICAgMjU0LFxuICAgICAgICAzNyxcbiAgICAgICAgOTgsXG4gICAgICAgIDQ4LFxuICAgICAgICAyMjEsXG4gICAgICAgIDU3LFxuICAgICAgICAyMCxcbiAgICAgICAgMTUsXG4gICAgICAgIDEwNCxcbiAgICAgICAgMjgsXG4gICAgICAgIDExLFxuICAgICAgICA0NixcbiAgICAgICAgMTYyLFxuICAgICAgICA4NSxcbiAgICAgICAgMTcxLFxuICAgICAgICA2MyxcbiAgICAgICAgMjQ2LFxuICAgICAgICAxMDYsXG4gICAgICAgIDIwNSxcbiAgICAgICAgMTA0LFxuICAgICAgICA5LFxuICAgICAgICAxODYsXG4gICAgICAgIDE5MCxcbiAgICAgICAgMTExLFxuICAgICAgICA4MixcbiAgICAgICAgMjA3LFxuICAgICAgICAzMyxcbiAgICAgICAgOTQsXG4gICAgICAgIDExMixcbiAgICAgICAgMzcsXG4gICAgICAgIDYxLFxuICAgICAgICAyMjYsXG4gICAgICAgIDIyLFxuICAgICAgICAyMTUsXG4gICAgICAgIDY5LFxuICAgICAgICA1OSxcbiAgICAgICAgMTMzLFxuICAgICAgICAyMTIsXG4gICAgICAgIDE2NixcbiAgICAgICAgMTkwLFxuICAgICAgICA4OCxcbiAgICAgICAgNjcsXG4gICAgICAgIDI1MyxcbiAgICAgICAgOTAsXG4gICAgICAgIDE3OSxcbiAgICAgICAgNyxcbiAgICAgICAgOTIsXG4gICAgICAgIDE1MCxcbiAgICAgICAgMTkyLFxuICAgICAgICAxMTcsXG4gICAgICAgIDYzLFxuICAgICAgICAxNDFcbiAgICAgIF1cbiAgICB9LFxuICAgIFwia2V5SWRcIjogMVxuICB9LFxuICBcInJlZ2lzdHJhdGlvbklkXCI6IDIyMyxcbiAgXCJhZHZTZWNyZXRLZXlcIjogXCI2anFOcStma04rNm5QWmkzaHE5dFI0YXJmeG9MbTN5TWRMeXVDSmRYNk9NPVwiLFxuICBcInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlc1wiOiBbXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjI1NDc5NzEwMTkzMkBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImZyb21NZVwiOiB0cnVlLFxuICAgICAgICBcImlkXCI6IFwiNkQ3NjQxODRFQ0JBOTk1NDhBM0Q5NUFFNDcyNTZBMEZcIlxuICAgICAgfSxcbiAgICAgIFwibWVzc2FnZVRpbWVzdGFtcFwiOiAxNzIwNTEzOTA1XG4gICAgfSxcbiAgICB7XG4gICAgICBcImtleVwiOiB7XG4gICAgICAgIFwicmVtb3RlSmlkXCI6IFwiMjU0Nzk3MTAxOTMyQHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCJGQ0Q2OTQzQTA2NEMwNDE1RkRDNkQ2NzBCRjUwRUY3M1wiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3MjA1MTM5MDhcbiAgICB9XG4gIF0sXG4gIFwibmV4dFByZUtleUlkXCI6IDMxLFxuICBcImZpcnN0VW51cGxvYWRlZFByZUtleUlkXCI6IDMxLFxuICBcImFjY291bnRTeW5jQ291bnRlclwiOiAxLFxuICBcImFjY291bnRTZXR0aW5nc1wiOiB7XG4gICAgXCJ1bmFyY2hpdmVDaGF0c1wiOiBmYWxzZVxuICB9LFxuICBcImRldmljZUlkXCI6IFwiUzJvNjRNNWxSSTIyZWNOYWJBUW5nUVwiLFxuICBcInBob25lSWRcIjogXCIzMzAyMGE2Ni1mZTlmLTQ1OTAtODcyZC04OWM0MjIzMjM4ZTdcIixcbiAgXCJpZGVudGl0eUlkXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMTQwLFxuICAgICAgMTY2LFxuICAgICAgNTksXG4gICAgICAyNTQsXG4gICAgICAxMDcsXG4gICAgICA5NSxcbiAgICAgIDE4NixcbiAgICAgIDIzLFxuICAgICAgMTYwLFxuICAgICAgMjQ0LFxuICAgICAgMTk0LFxuICAgICAgMTk0LFxuICAgICAgMTY3LFxuICAgICAgMTI0LFxuICAgICAgNDMsXG4gICAgICAxMzYsXG4gICAgICAyMjMsXG4gICAgICAxMzIsXG4gICAgICA3MSxcbiAgICAgIDE4NFxuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RlcmVkXCI6IGZhbHNlLFxuICBcImJhY2t1cFRva2VuXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgODcsXG4gICAgICAyMTcsXG4gICAgICAxODksXG4gICAgICAxOTAsXG4gICAgICAyNTIsXG4gICAgICAxMDksXG4gICAgICAyMyxcbiAgICAgIDMwLFxuICAgICAgMTU1LFxuICAgICAgMTAwLFxuICAgICAgNDksXG4gICAgICAyNCxcbiAgICAgIDQ0LFxuICAgICAgNDEsXG4gICAgICA5MixcbiAgICAgIDE2MixcbiAgICAgIDI2LFxuICAgICAgMjQ3LFxuICAgICAgMTYsXG4gICAgICAxNzhcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uXCI6IHt9LFxuICBcImFjY291bnRcIjoge1xuICAgIFwiZGV0YWlsc1wiOiBcIkNMdnB3WnNDRU92cXM3UUdHQVVnQUNnQVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZUtleVwiOiBcIlk1eVpGWnB5Zk1sSWRNZGZ6dWR3K21YeHFoY0dRUUQyNzI4U2JMd1hReGM9XCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlXCI6IFwiajl0NWc1SGdxQmQzS0JSTEJxZTVLOHdqZlNkdUlwcDI3ejlDZ2ZxZWszZ0pIZW1rd0JhVW9Keld0TWhqZ0F3QlpXZWtXTlMybWRWQkVhQ0hjRVlOQXc9PVwiLFxuICAgIFwiZGV2aWNlU2lnbmF0dXJlXCI6IFwibUorOVkvcWhPa1lJNWlraVVzY1JHSlJYaWhIa1hZc2U5UTFkYVdTRWJlaHJsOGhRcnc4cDdjcmNCR2JlWEw5MlhwN0FtcW96ckhER2RaMWdCblBhZ3c9PVwiXG4gIH0sXG4gIFwibWVcIjoge1xuICAgIFwiaWRcIjogXCIyNTQ3OTcxMDE5MzI6MjhAcy53aGF0c2FwcC5uZXRcIixcbiAgICBcImxpZFwiOiBcIjEzODQ3MDE4MTg0MzEwMDoyOEBsaWRcIixcbiAgICBcIm5hbWVcIjogXCJtaWNoYWVsXCJcbiAgfSxcbiAgXCJzaWduYWxJZGVudGl0aWVzXCI6IFtcbiAgICB7XG4gICAgICBcImlkZW50aWZpZXJcIjoge1xuICAgICAgICBcIm5hbWVcIjogXCIyNTQ3OTcxMDE5MzI6MjhAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJkZXZpY2VJZFwiOiAwXG4gICAgICB9LFxuICAgICAgXCJpZGVudGlmaWVyS2V5XCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgNSxcbiAgICAgICAgICA5OSxcbiAgICAgICAgICAxNTYsXG4gICAgICAgICAgMTUzLFxuICAgICAgICAgIDIxLFxuICAgICAgICAgIDE1NCxcbiAgICAgICAgICAxMTQsXG4gICAgICAgICAgMTI0LFxuICAgICAgICAgIDIwMSxcbiAgICAgICAgICA3MixcbiAgICAgICAgICAxMTYsXG4gICAgICAgICAgMTk5LFxuICAgICAgICAgIDk1LFxuICAgICAgICAgIDIwNixcbiAgICAgICAgICAyMzEsXG4gICAgICAgICAgMTEyLFxuICAgICAgICAgIDI1MCxcbiAgICAgICAgICAxMDEsXG4gICAgICAgICAgMjQxLFxuICAgICAgICAgIDE3MCxcbiAgICAgICAgICAyMyxcbiAgICAgICAgICA2LFxuICAgICAgICAgIDY1LFxuICAgICAgICAgIDAsXG4gICAgICAgICAgMjQ2LFxuICAgICAgICAgIDIzOSxcbiAgICAgICAgICAxMTEsXG4gICAgICAgICAgMTgsXG4gICAgICAgICAgMTA4LFxuICAgICAgICAgIDE4OCxcbiAgICAgICAgICAyMyxcbiAgICAgICAgICA2NyxcbiAgICAgICAgICAyM1xuICAgICAgICBdXG4gICAgICB9XG4gICAgfVxuICBdLFxuICBcInBsYXRmb3JtXCI6IFwiYW5kcm9pZFwiLFxuICBcImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcFwiOiAxNzIwNTEzOTAzLFxuICBcIm15QXBwU3RhdGVLZXlJZFwiOiBcIkFBQUFBS1hOXCJcbn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFLWEouanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJNY2h1ZXJJL2dCOFlybzBTQ2pTZjdlejdMZlVaRTFhdnhJTms3VnhhU1Z3PVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjU5NDU3MjQ3MSxcImN1cnJlbnRJbmRleFwiOjEsXCJkZXZpY2VJbmRleGVzXCI6WzBdfSxcInRpbWVzdGFtcFwiOlwiMTcxNzA3MDU2NTEwNlwifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUtYSy5qc29uIjogIntcImtleURhdGFcIjpcIkZZdXRXWUhUZWl2ZUxoMGRkSmhsZElFUVlLbnJCcW54REQ2OEVVUHFxODg9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6NTk0NTcyNDcyLFwiY3VycmVudEluZGV4XCI6MSxcImRldmljZUluZGV4ZXNcIjpbMCwxXX0sXCJ0aW1lc3RhbXBcIjpcIjBcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFLWEwuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCIxVUpWU1U1OU5WOG5nK0ZWYUI0UzJRa0V1VlVmMDRaeFhjY3o5WTVobHNFPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjU5NDU3MjQ3MyxcImN1cnJlbnRJbmRleFwiOjEsXCJkZXZpY2VJbmRleGVzXCI6WzAsMV19LFwidGltZXN0YW1wXCI6XCIxNzE3NTYxNzk3ODE5XCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBS1hNLmpzb24iOiAie1wia2V5RGF0YVwiOlwiLzlBVFZQcWlsUGRnNUo1eXA4MUlScnNzVXVMTkJHemJKVVE4ZSs5WlR2az1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjo1OTQ1NzI0NzQsXCJjdXJyZW50SW5kZXhcIjoxLFwiZGV2aWNlSW5kZXhlc1wiOlswLDFdfSxcInRpbWVzdGFtcFwiOlwiMFwifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUtYTi5qc29uIjogIntcImtleURhdGFcIjpcIjdkKzhWS2xEV09SSkxDcjFudThsL05nUHpuLzBGUkV3Z1g3Zi9Hc3FnZE09XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6NTk0NTcyNDc1LFwiY3VycmVudEluZGV4XCI6MSxcImRldmljZUluZGV4ZXNcIjpbMCwxXX0sXCJ0aW1lc3RhbXBcIjpcIjBcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFLWE8uanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJTOVNSQWswS2dYQkF2aHJRNkFLMGtBMk9tMnNtL1FWTGNJOGhibWhoUHFZPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjU5NDU3MjQ3NSxcImN1cnJlbnRJbmRleFwiOjIsXCJkZXZpY2VJbmRleGVzXCI6WzAsMV19LFwidGltZXN0YW1wXCI6XCIxNzE5NTc0NTIwNjE3XCJ9Igp9

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "1.3.8",
  caption : global.caption || "" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "",
  packname: process.env.PACK_NAME || "",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "Suhail",


  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,


  WORKTYPE: process.env.WORKTYPE || process.env.MODE|| "private",
  LANG: ( process.env.THEME ||  "SUHAIL"  ).toUpperCase(),



};



global.ELEVENLAB_API_KEY = process.env.ELEVENLAB_API_KEY || "";
global.aitts_Voice_Id = process.env.AITTS_ID|| "37";





















global.rank = "updated"
global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
  //aitts_Voice_Id : process.env.AITTS_ID || "37",
  //ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY  || "",
